/*
 * generated by Xtext 2.14.0
 */
package dsl.finalproject.validation

import dsl.finalproject.fp.Task
import dsl.finalproject.fp.Obstacles
import dsl.finalproject.fp.ColorWithName
import dsl.finalproject.fp.Color
import dsl.finalproject.fp.FpPackage
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class FpValidator extends AbstractFpValidator {
	


	@Check
	def avoidWithBlack(Obstacles obstacle) {
		if (obstacle==ColorWithName) 
		{
			if (ColorWithName==Color.BLACK) {
				warning('You try to avoid black on a black space.',null)
			}
		}
	}
	
}
